all:
	g++ Kart.cpp User.cpp Wallet.cpp main.cpp Api.cpp --std=c++11 -I/opt/homebrew/Cellar/rapidjson/1.1.0/include -I/opt/homebrew/Cellar/curl/8.0.1/include -L/opt/homebrew/Cellar/curl/8.0.1/lib -lcurl && ./a.out
